import {
  pgTable,
  text,
  timestamp,
  jsonb,
  boolean,
  serial,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// Raw speeches pulled from GovInfo Congressional Record
export const speeches = pgTable(
  "speeches",
  {
    id: serial("id").primaryKey(),
    granuleId: text("granule_id").notNull().unique(),
    title: text("title").notNull(),
    speaker: text("speaker"), // Parsed from text
    party: text("party"), // R, D, I
    chamber: text("chamber").notNull(), // HOUSE, SENATE
    date: timestamp("date", { mode: "date" }).notNull(),
    rawHtml: text("raw_html").notNull(),
    plainText: text("plain_text").notNull(),
    topics: jsonb("topics").$type<string[]>().default([]),
    processed: boolean("processed").default(false),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    index("speeches_date_idx").on(table.date),
    index("speeches_party_idx").on(table.party),
    index("speeches_chamber_idx").on(table.chamber),
    uniqueIndex("speeches_granule_idx").on(table.granuleId),
  ]
);

// Daily briefs generated by the agent pipeline
export const briefs = pgTable(
  "briefs",
  {
    id: serial("id").primaryKey(),
    date: timestamp("date", { mode: "date" }).notNull(),
    topic: text("topic").notNull(),
    slug: text("slug").notNull(),

    // Steelmanned positions
    redPosition: text("red_position").notNull(),
    bluePosition: text("blue_position").notNull(),

    // Bridge analysis
    sharedValues: jsonb("shared_values").$type<string[]>().default([]),
    differences: jsonb("differences").$type<string[]>().default([]),
    compromisePaths: jsonb("compromise_paths").$type<string[]>().default([]),

    // Democracy guard
    democracyCheck: text("democracy_check").notNull(),
    democracyFlagged: boolean("democracy_flagged").default(false),

    // Policy draft
    policyDraft: text("policy_draft"),

    // Full agent conversation for transparency
    agentConversation: jsonb("agent_conversation")
      .$type<AgentMessage[]>()
      .default([]),

    // Source speech metadata for attribution
    sourceSpeechMeta: jsonb("source_speech_meta")
      .$type<SpeechMeta[]>()
      .default([]),

    // Opportunity Scout score and reasoning
    collaborationScore: text("collaboration_score"),
    collaborationReason: text("collaboration_reason"),

    // Legacy source speech IDs
    sourceSpeechIds: jsonb("source_speech_ids")
      .$type<number[]>()
      .default([]),

    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    index("briefs_date_idx").on(table.date),
    index("briefs_slug_idx").on(table.slug),
  ]
);

// Types
export type SpeechMeta = {
  granuleId: string;
  speaker: string | null;
  party: "R" | "D" | "I" | "unknown";
  chamber: "HOUSE" | "SENATE";
  title: string;
  corePosition: string;
};

export type AgentMessage = {
  agent: string;
  role: "intake" | "red" | "blue" | "bridge" | "guard" | "drafter" | "scout";
  content: string;
  timestamp: string;
};

// Bipartisan bills from Congress.gov
export const bills = pgTable(
  "bills",
  {
    id: serial("id").primaryKey(),
    congress: text("congress").notNull(),
    billType: text("bill_type").notNull(), // hr, s, hjres, sjres
    billNumber: text("bill_number").notNull(),
    title: text("title").notNull(),
    policyArea: text("policy_area"),
    legislativeSubjects: jsonb("legislative_subjects").$type<string[]>().default([]),

    // Sponsor
    sponsorName: text("sponsor_name"),
    sponsorParty: text("sponsor_party"), // R, D, I
    sponsorState: text("sponsor_state"),

    // Cosponsor party counts
    cosponsorCountR: text("cosponsor_count_r").default("0"),
    cosponsorCountD: text("cosponsor_count_d").default("0"),
    cosponsorCountI: text("cosponsor_count_i").default("0"),
    cosponsorTotal: text("cosponsor_total").default("0"),

    // Bipartisan score: min(R,D) / max(R,D), 0-1
    bipartisanScore: text("bipartisan_score"),

    // Status
    status: text("status").notNull(), // introduced, committee, floor, passed_one, passed_both, enacted, vetoed
    latestActionText: text("latest_action_text"),
    latestActionDate: timestamp("latest_action_date", { mode: "date" }),

    congressGovUrl: text("congress_gov_url"),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("bills_congress_type_number_idx").on(table.congress, table.billType, table.billNumber),
    index("bills_bipartisan_score_idx").on(table.bipartisanScore),
    index("bills_status_idx").on(table.status),
    index("bills_policy_area_idx").on(table.policyArea),
  ]
);

// Links bills to CommonGround topic slugs
export const billTopicLinks = pgTable(
  "bill_topic_links",
  {
    id: serial("id").primaryKey(),
    billId: serial("bill_id").notNull(),
    topicSlug: text("topic_slug").notNull(),
    confidence: text("confidence"), // high, medium, low
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("bill_topic_link_idx").on(table.billId, table.topicSlug),
    index("bill_topic_slug_idx").on(table.topicSlug),
  ]
);

export type Speech = typeof speeches.$inferSelect;
export type NewSpeech = typeof speeches.$inferInsert;
export type Brief = typeof briefs.$inferSelect;
export type NewBrief = typeof briefs.$inferInsert;
export type Bill = typeof bills.$inferSelect;
export type NewBill = typeof bills.$inferInsert;
export type BillTopicLink = typeof billTopicLinks.$inferSelect;
