import {
  pgTable,
  text,
  timestamp,
  jsonb,
  boolean,
  serial,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// Raw speeches pulled from GovInfo Congressional Record
export const speeches = pgTable(
  "speeches",
  {
    id: serial("id").primaryKey(),
    granuleId: text("granule_id").notNull().unique(),
    title: text("title").notNull(),
    speaker: text("speaker"), // Parsed from text
    party: text("party"), // R, D, I
    chamber: text("chamber").notNull(), // HOUSE, SENATE
    date: timestamp("date", { mode: "date" }).notNull(),
    rawHtml: text("raw_html").notNull(),
    plainText: text("plain_text").notNull(),
    topics: jsonb("topics").$type<string[]>().default([]),
    processed: boolean("processed").default(false),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    index("speeches_date_idx").on(table.date),
    index("speeches_party_idx").on(table.party),
    index("speeches_chamber_idx").on(table.chamber),
    uniqueIndex("speeches_granule_idx").on(table.granuleId),
  ]
);

// Daily briefs generated by the agent pipeline
export const briefs = pgTable(
  "briefs",
  {
    id: serial("id").primaryKey(),
    date: timestamp("date", { mode: "date" }).notNull(),
    topic: text("topic").notNull(),
    slug: text("slug").notNull(),

    // Steelmanned positions
    redPosition: text("red_position").notNull(),
    bluePosition: text("blue_position").notNull(),

    // Bridge analysis
    sharedValues: jsonb("shared_values").$type<string[]>().default([]),
    differences: jsonb("differences").$type<string[]>().default([]),
    compromisePaths: jsonb("compromise_paths").$type<string[]>().default([]),

    // Democracy guard
    democracyCheck: text("democracy_check").notNull(),
    democracyFlagged: boolean("democracy_flagged").default(false),

    // Policy draft
    policyDraft: text("policy_draft"),

    // Full agent conversation for transparency
    agentConversation: jsonb("agent_conversation")
      .$type<AgentMessage[]>()
      .default([]),

    // Source speech metadata for attribution
    sourceSpeechMeta: jsonb("source_speech_meta")
      .$type<SpeechMeta[]>()
      .default([]),

    // Opportunity Scout score and reasoning
    collaborationScore: text("collaboration_score"),
    collaborationReason: text("collaboration_reason"),

    // Legacy source speech IDs
    sourceSpeechIds: jsonb("source_speech_ids")
      .$type<number[]>()
      .default([]),

    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    index("briefs_date_idx").on(table.date),
    index("briefs_slug_idx").on(table.slug),
  ]
);

// Types
export type SpeechMeta = {
  granuleId: string;
  speaker: string | null;
  party: "R" | "D" | "I" | "unknown";
  chamber: "HOUSE" | "SENATE";
  title: string;
  corePosition: string;
};

export type AgentMessage = {
  agent: string;
  role: "intake" | "red" | "blue" | "bridge" | "guard" | "drafter" | "scout";
  content: string;
  timestamp: string;
};

export type Speech = typeof speeches.$inferSelect;
export type NewSpeech = typeof speeches.$inferInsert;
export type Brief = typeof briefs.$inferSelect;
export type NewBrief = typeof briefs.$inferInsert;
